#! /usr/bin/env python3

from os import chdir
from os.path import dirname
from pathlib import Path
import sys
from subprocess import run


def main():

    run_accession_list = [
        "CRR240976",
        "CRR240977",
        "CRR240978",
        "CRR240979",
        "CRR240980",
        "CRR240981",
        "CRR240982",
        "CRR240983",
        "CRR240984",
        "CRR240985",
        "CRR240986",
        "CRR240987",
        "CRR240988",
        "CRR240989",
        "CRR240990",
        "CRR240991",
        "CRR240992",
        "CRR240993"
    ]

    script_path = Path(dirname(Path(sys.argv[0]).resolve()))
    prg_path = script_path / ".." / "programs" / "trimmomatic"
    dat_path = script_path / ".." / "data"
    jar = "trimmomatic-0.39.jar"
    adapter_path = "adapters" + "/" + "TruSeq3-PE.fa"

    chdir(prg_path)
    for run_accession in run_accession_list:

        src_forward_path = dat_path / (run_accession + "_f1.fastq.gz")
        src_reverse_path = dat_path / (run_accession + "_r2.fastq.gz")
        dest_forward_path_p = dat_path / (run_accession + "_f1.trim.p.fastq.gz")
        dest_forward_path_u = dat_path / (run_accession + "_f1.trim.u.fastq.gz")
        dest_reverse_path_p = dat_path / (run_accession + "_r2.trim.p.fastq.gz")
        dest_reverse_path_u = dat_path / (run_accession + "_r2.trim.u.fastq.gz")

        run([
                "java",
                "-jar", jar,
                "PE",
                "-threads", "8"
            ]
            + [
                src_forward_path,
                src_reverse_path,
                dest_forward_path_p,
                dest_forward_path_u,
                dest_reverse_path_p,
                dest_reverse_path_u
            ]
            + [
                "ILLUMINACLIP:" + adapter_path + ":2:30:10:2:True",
                "HEADCROP:12",
                "LEADING:3",
                "TRAILING:3",
                "SLIDINGWINDOW:4:15",
                "MINLEN:100"
            ])


if __name__ == "__main__":
    main()
